"""Trains a RandomForest model predicting Stress/Anxiety/Depression levels (0-10)
from lifestyle factors, on the synthetic dataset generated by generate_dataset.py.
Run this after regenerating the dataset. Prints held-out R²/MAE honestly — this is
a demo model on synthetic data, not a clinical instrument."""

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

NUMERIC_FEATURES = [
    "Age",
    "Sleep_Duration",
    "Exercise_Frequency",
    "Social_Media_Usage",
    "Work_Hours",
    "Support_System",
    "Self_Care_Activities",
]
CATEGORICAL_FEATURES = ["Gender", "Region", "Financial_Stress", "Relationship_Issues"]
TARGETS = ["Stress_Level", "Anxiety_Level", "Depression_Level"]


def train():
    df = pd.read_csv("data/synthetic_wellness_dataset.csv")

    X = df[NUMERIC_FEATURES + CATEGORICAL_FEATURES]
    y = df[TARGETS]

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    preprocessor = ColumnTransformer(
        transformers=[
            ("cat", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES),
        ],
        remainder="passthrough",
    )

    model = Pipeline(
        steps=[
            ("preprocess", preprocessor),
            ("regressor", MultiOutputRegressor(RandomForestRegressor(n_estimators=200, max_depth=8, random_state=42))),
        ]
    )

    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    print("Held-out test set performance (synthetic data):")
    for i, target in enumerate(TARGETS):
        r2 = r2_score(y_test[target], predictions[:, i])
        mae = mean_absolute_error(y_test[target], predictions[:, i])
        print(f"  {target}: R2={r2:.3f}  MAE={mae:.2f} (scale is 0-10)")

    joblib.dump(model, "models/wellness_predictor.joblib")
    print("\nSaved model to models/wellness_predictor.joblib")


if __name__ == "__main__":
    train()
