"""Trains a model predicting Stress/Anxiety/Depression levels (0-10) from lifestyle
factors, on the synthetic dataset generated by generate_dataset.py.

Rather than assuming RandomForest (or any single algorithm) is "best," this compares
several candidate regressors via 5-fold cross-validation on the training set and picks
the one with the highest average R2 across the three targets. The full comparison
(per-model, per-target R2/MAE) is saved to models/model_comparison.json alongside the
model, so the choice is backed by numbers rather than habit.

Run this after regenerating the dataset. Prints held-out R2/MAE honestly — this is a
demo model on synthetic data, not a clinical instrument (see generate_dataset.py).
"""

import json
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import KFold, cross_validate, train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

NUMERIC_FEATURES = [
    "Age",
    "Sleep_Duration",
    "Exercise_Frequency",
    "Social_Media_Usage",
    "Work_Hours",
    "Support_System",
    "Self_Care_Activities",
]
CATEGORICAL_FEATURES = ["Gender", "Region", "Financial_Stress", "Relationship_Issues"]
TARGETS = ["Stress_Level", "Anxiety_Level", "Depression_Level"]

CANDIDATES = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(alpha=1.0, random_state=42),
    "RandomForest": RandomForestRegressor(n_estimators=200, max_depth=8, random_state=42),
    "GradientBoosting": GradientBoostingRegressor(random_state=42),
}


def _preprocessor():
    return ColumnTransformer(
        transformers=[("cat", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES)],
        remainder="passthrough",
    )


def compare_candidates(X_train: pd.DataFrame, y_train: pd.DataFrame) -> dict:
    """5-fold CV per target per candidate. Returns {name: {per_target: {...}, avg_r2: ...}}."""
    kfold = KFold(n_splits=5, shuffle=True, random_state=42)
    results = {}
    for name, estimator in CANDIDATES.items():
        per_target = {}
        for target in TARGETS:
            pipeline = Pipeline(steps=[("preprocess", _preprocessor()), ("regressor", estimator)])
            scores = cross_validate(
                pipeline,
                X_train,
                y_train[target],
                cv=kfold,
                scoring={"r2": "r2", "mae": "neg_mean_absolute_error"},
            )
            per_target[target] = {
                "r2": float(np.mean(scores["test_r2"])),
                "mae": float(-np.mean(scores["test_mae"])),
            }
        avg_r2 = float(np.mean([m["r2"] for m in per_target.values()]))
        results[name] = {"per_target": per_target, "avg_r2": avg_r2}
    return results


def train():
    df = pd.read_csv("data/synthetic_wellness_dataset.csv")
    X = df[NUMERIC_FEATURES + CATEGORICAL_FEATURES]
    y = df[TARGETS]
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    print("5-fold cross-validation on the training set (synthetic data):\n")
    comparison = compare_candidates(X_train, y_train)
    ranked = sorted(comparison.items(), key=lambda kv: kv[1]["avg_r2"], reverse=True)
    for name, result in ranked:
        print(f"  {name:18s} avg R2={result['avg_r2']:.3f}")
        for target, m in result["per_target"].items():
            print(f"      {target:18s} R2={m['r2']:.3f}  MAE={m['mae']:.2f}")

    winner_name, winner_result = ranked[0]
    print(f"\nSelected: {winner_name} (highest average cross-validated R2: {winner_result['avg_r2']:.3f})")

    final_model = Pipeline(
        steps=[
            ("preprocess", _preprocessor()),
            ("regressor", MultiOutputRegressor(CANDIDATES[winner_name])),
        ]
    )
    final_model.fit(X_train, y_train)
    predictions = final_model.predict(X_test)

    print("\nHeld-out test set performance of the selected model:")
    test_metrics = {}
    for i, target in enumerate(TARGETS):
        r2 = r2_score(y_test[target], predictions[:, i])
        mae = mean_absolute_error(y_test[target], predictions[:, i])
        test_metrics[target] = {"r2": round(float(r2), 3), "mae": round(float(mae), 2)}
        print(f"  {target}: R2={r2:.3f}  MAE={mae:.2f} (scale is 0-10)")

    Path("models").mkdir(exist_ok=True)
    joblib.dump(final_model, "models/wellness_predictor.joblib")

    report = {"selected_model": winner_name, "cross_validation": comparison, "held_out_test": test_metrics}
    Path("models/model_comparison.json").write_text(json.dumps(report, indent=2))

    print("\nSaved model to models/wellness_predictor.joblib")
    print("Saved comparison report to models/model_comparison.json")


if __name__ == "__main__":
    train()
